CI/CD tsconfig.json(16,5): error TS5101: Option 'baseUrl' is deprecated and will stop functioning in TypeScript 7.0. Specify compilerOption 'ignoreDeprecations: 6.0' to silence this error.